version: '3.7'

services:
    db-desafio03-02:
        image: postgres
        container_name: db-desafio03-02
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker 
            - POSTGRES_DB=queries_challenge
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    app:
        build: .
        container_name: desafio03.02
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - db-desafio03-02
volumes:
    pgdata:
        driver: local